### ISSUE TITLE
Add phpmyadmin to the script

### ISSUE THREAD

**Issue by shoujii** [shoujii/NeXt-Server#16]
Add phpmyadmin to the script

**Comment by shoujii** [comment]
working now with https://github.com/shoujii/NeXt-Server/commit/bd82fea808f07f7c6490d494b7bc393a459fac2c

check folders + config.inc.php if settings up2date

**Comment by shoujii** [comment]
The configuration file now needs a secret passphrase (blowfish_secret).

**Comment by BoBBer446** [comment]
Pma Works, Login Works, MySQL is working

**Comment by shoujii** [comment]
PMA login with root mysql user is possible, there was a rerstriction in the past days in my opinion (pma forbid to login with mysql root) -> the reason why we created another user

**Comment by BoBBer446** [comment]
root login is disabled
new httpauth user is generated (no longer prsadminuser)

**Comment by shoujii** [comment]
Closed, working like a charm now
