### ISSUE TITLE
Make all services standalone installation ready if possible

### ISSUE THREAD

**Issue by shoujii** [shoujii/NeXt-Server#20]
Make all services standalone installation ready if possible
openssh
openssl
webserver only
mailserver only 
...

**Comment by TiggaStyle** [comment]
ggf. eine Auswahl was will ich mit welchen Einstellungen,

**Comment by shoujii** [comment]
Closed, we will only support 2 variants:
- Webserver only
- Web + Mailserver

To many options = not possible to maintain
