### ISSUE TITLE
Add nextcloud to the script

### ISSUE THREAD

**Issue by shoujii** [shoujii/NeXt-Server#21]
Add nextcloud to the script

**Comment by TiggaStyle** [comment]
NextCloud wäre Nett

**Comment by shoujii** [comment]
Added with https://github.com/shoujii/NeXt-Server/commit/c7a8ae184673f1e6eab568b82401d92180182348

Please test / report Bugs

**Comment by shoujii** [comment]
Buggy atm

**Comment by shoujii** [comment]
Working :)
