### ISSUE TITLE
Auto detect domain

### ISSUE THREAD

**Issue by shoujii** [shoujii/NeXt-Server#25]
Auto detect domain reverse lookup?
The script will use this domain, unless the user accepts it... otherwise he can enter the domain manually.

**Comment by shoujii** [comment]
https://github.com/shoujii/NeXt-Server/commit/2a472dac0916447c4699ec454c0b45cc1e81b4d9
boom magic :)

But more testing needed!

**Comment by BoBBer446** [comment]
Super gemacht. Läuft. Voraussetzung ist das DNS richtig gesetzt ist. Allerdings ist es ja eh eine Grundvoraussetzung.

Läuft.

**Comment by shoujii** [comment]
Wenn man mehrere Domains via DNS gesetzt hat, dann kommt ".:" vielleicht eine Meldung einbauen dass das Script die Domain nicht erkennen konnte?

**Comment by shoujii** [comment]
Improved with https://github.com/shoujii/NeXt-Server/commit/4b92373213614c94cad9773f51fdded8d8a813ac testing needed

**Comment by VeePay** [comment]
Works fine

**Comment by shoujii** [comment]
Super, closed! :)
