### ISSUE TITLE
Fix pagespeed 

### ISSUE THREAD

**Issue by shoujii** [shoujii/NeXt-Server#26]
Pagespeed changed a lot, look over it

**Comment by BoBBer446** [comment]
maybe fixed
https://github.com/shoujii/NeXt-Server/commit/ef0056a1a58faa4c72b17e9cf898ef2c1bc69888

**Comment by shoujii** [comment]
Fixed with https://github.com/shoujii/NeXt-Server/commit/642b62c40b37f7363a98127e599544fdf0ff697a
