### ISSUE TITLE
Firewall configuration

### ISSUE THREAD

**Issue by VeePay** [shoujii/NeXt-Server#30]
- Port öffnen -> vorhanden
- Port schließen -> vorhanden
- Status aller Einträge -> wünschenswert
- automatische Einrichtung der benötigten Ports, Rest geschlossen -> wünschenswert

**Comment by BoBBer446** [comment]
Es werden alle Ports geschlossen bzw. nur die geöffnet, die benötigt werden.
Status der Eintrage? Du meinst am Ende eine Übersicht aller offenen Ports?

**Comment by VeePay** [comment]
Richtig.
Eine Übersicht aller aktuell offenen Ports.

**Comment by BoBBer446** [comment]
okay, kommt.

**Comment by shoujii** [comment]
Vll die Zeile aus der /etc/arno-iptables-firewall/firewall.conf auslesen anstatt alle Ports manuell eintragen zu lassen.
In der menu_firewall.sh könnte es dann eine show_ports Funktion geben, die alle TCP und UDP Ports anzeigt.

**Comment by shoujii** [comment]
Geaddet mit https://github.com/shoujii/NeXt-Server/commit/a58380995c444b55673b6ca2fd92227a57d73e85

Bitte noch testen!

**Comment by VeePay** [comment]
Anzeige aller geöffneter Ports klappt einwandfrei. Es wäre noch schön, dass man die Ports auch noch manuell schließen könnte :-)
Zudem würde es die Konfiguration erheblich erleichtern, wenn eine mehrfach Nennung von Ports möglich wäre. Aktuell muss ein Port geöffnet werden und anschließend das Skript erneut ausgeführt werden.

**Comment by BoBBer446** [comment]
Wieso manuell schließen ? Es werden nur Ports geöffnet die das Script bzw. die Serverkonfiguration benötigt. 

Was genau soll eine mehrfach Nennung von Ports sein? Wenn du Ports öffnest machst du das in der /etc/arno-iptables-firewall/firewall.conf und lädst die Firewall config neu ein. 

Für weitere Fragen bitte immer ein neues issue öffnen damit es übersichtlich bleibt.

**Comment by shoujii** [comment]
Ports lassen sich nun via Menü schließen + danach wird das Menü direkt wieder gestartet :)
https://github.com/shoujii/NeXt-Server/commit/832c7a3e4d5d697f3a94af1177dca041b1ed9ab7
