### ISSUE TITLE
MYSQL USER HAVE ROOT but no permissions!

### ISSUE THREAD

**Issue by BoBBer446** [shoujii/NeXt-Server#33]
At the moment you can connect viva cli to mysql like this
`mysql -uroot -p`

then you have to copy your password
`PASSWORD FROM LOGININFORMATION`

Now create a new user
`CREATE USER 'NEWUSER'@'localhost';`

Create a database
`create database DATABASENAME;`

Give him permissions for specific database
`GRANT ALL PRIVILEGES ON DATABASENAME.* To 'NEWUSER'@'hostname' IDENTIFIED BY 'NEWPASSWORD';`

Login into new user
`mysql -uNEWUSER -p`

type password
`NEWPASSWORD`

Import a sql file to your database by use the database at first
`use DATABASENAME`

Now import content to database
`source /root/nxtdaten/db/DATABASEFILE.sql;`

in future the phpmyadmin will work

For further informations see mysql cli cheat sheets like this:
https://gist.github.com/hofmannsven/9164408

**Comment by TiggaStyle** [comment]
kennst du mysql_secure_installation

**Comment by BoBBer446** [comment]
Ja

**Comment by BoBBer446** [comment]
Fixed
