### ISSUE TITLE
Startscript Mailman

### ISSUE THREAD

**Issue by TiggaStyle** [shoujii/NeXt-Server#34]
vllt war/ist es nicht richtig installiert, aber nach einem Reboot startet Mailman nicht automatisch.

**Comment by shoujii** [comment]
Da handelt es sich tatsächlich um einen Bug!
Ich schaue es mir die Tage an.

**Comment by BoBBer446** [comment]
Wieso nicht in
`/etc/init.d/`

Mailman starten:
`/etc/init.d/mailman start`

Bei jedem Boot startet Mailman dann.

**Comment by BoBBer446** [comment]
/etc/crontab

@reboot root /root/NeXt-Server/cronjobs/startmailman.sh

chmod +x /root/NeXt-Server/cronjobs/startmailman.sh

/startmailman.sh:
cd /etc/mailman
npm start

**Comment by BoBBer446** [comment]
36d6b51

**Comment by BoBBer446** [comment]
bitte mal die ausgabe von
`cat /etc/crontab`

**Comment by VeePay** [comment]
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user  command
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#

**Comment by VeePay** [comment]
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user  command
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#

**Comment by BoBBer446** [comment]
cat /etc/crontab bitte

**Comment by VeePay** [comment]
Mein vorheriger kommentar war der Inhalt vom crontab. Leider formatiert github diesen so komisch

**Comment by BoBBer446** [comment]
@VeePay ne nicht schlimm habe ich falsch gelesen auf handy mit halboffenen Augen :/

Von wann war die installation des scripts?
Aktuell sollte der Cronjob drinnen sein:
```
root@mail:~# cat /etc/crontab                                                                                                                                                 
# /etc/crontab: system-wide crontab                                                                                                                                           
# Unlike any other crontab you don't have to run the `crontab'                                                                                                                
# command to install the new version when you edit this file                                                                                                                  
# and files in /etc/cron.d. These files also have username fields,                                                                                                            
# that none of the other crontabs do.                                                                                                                                         
                                                                                                                                                                              
SHELL=/bin/sh                                                                                                                                                                 
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin                                                                                                             
                                                                                                                                                                              
# m h dom mon dow user  command                                                                                                                                               
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly                                                                                                           
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )                                                                           
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )                                                                          
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )                                                                         
#                                                                                                                                                                             
@reboot root /root/NeXt-Server/cronjobs/startmailman.sh                                                                                                                       
root@mail:~#             
```

**Comment by VeePay** [comment]
Skript install war am 07.06.18 um 15 Uhr

**Comment by BoBBer446** [comment]
der manuelle Aufruf von 
```
bash /root/NeXt-Server/cronjobs/startmailman.sh
```
 klappt. Dann startet er mailman.

Die reboot.txt ist auch da. Also der Cronjob klappt aber trotzdem klappt etwas nicht....

**Comment by shoujii** [comment]
fixed https://github.com/shoujii/NeXt-Server/commit/e5b3a5d3075bad05c615f6a19b1f2064d2715acf
