### ISSUE TITLE
vhost ohne SSL

### ISSUE THREAD

**Issue by TiggaStyle** [shoujii/NeXt-Server#35]
Ich würde gerne noch einen vhost ohne SSL erstellen können

**Comment by BoBBer446** [comment]
Ziel ? Also gibt es ein spezielles Tool welches ungeschützte Verbindungen benötigt ? Wir versuchen viel Wert auf Sicherheit zu legen. Aktuell fällt mir kein Grund ein heute noch SSL freie vhosts anzubieten. Zumindest nicht abseits der Anfänger User.

**Comment by TiggaStyle** [comment]
Für Apps, die spezielle Urls ansurfen und dort Daten abholen.
oder Anwendungen die kein SSL unterstützen.

**Comment by shoujii** [comment]
Vielleicht realisieren wir das mal als Addon, aber in der STandard Installation möchte ich eher unbedarften Nutzern eher nicht die Option geben.
Bei einem Addon würden dann aber auch x Warnungen davor stehen :D

**Comment by TiggaStyle** [comment]
Das meiste was ich schreibe ist alles nen Addon

**Comment by shoujii** [comment]
Ich würde das hier erstmal schließen.
In Zukunft könnte man einen Vhost Generator anbieten.
Wobei der Bedarf auch nicht der größte sein dürfte, bzw die betroffenen User wohl auch entsprechend technisch versiert sind.
