### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by TiggaStyle** [shoujii/NeXt-Server#36]
Da ggf. die meisten dann Wordpress nutzen, könnte man dies beim Vhost erstellen direkt angeben, der Installiert dann das neueste mit Sicherheitsoptionen im nginx und erstellt DB und User usw.

**Comment by BoBBer446** [comment]
Das kommt auf die Zielgruppe an. Es gibt auch sehr viele die einen TeamSpeak Server wollen. Auch Foren (da gibt es ja deutlich mehr Auswahl) sind beliebt oder CMS Systeme wie joomla, drupal oder auch webspell.

Man muss also nun überlegen was man hier anbieten will. Ein Server Script zum erstellen eines web und Mailservers oder soll es am Ende eine eierlegende wollmilchsau werden.

Ich verstehe das jedoch Interesse daran. Gerade als Addon wäre das sicherlich machbar und eine Idee. Da gäbe es ja dann auch schnelle Möglichkeiten das umzusetzen :)

**Comment by BoBBer446** [comment]
Erledigt. WP ist als Addon installierbar. Aktuell im root path mit wp harding
