### ISSUE TITLE
installers like wordpress cant create new database

### ISSUE THREAD

**Issue by BoBBer446** [shoujii/NeXt-Server#38]
If the user want install a script like wordpress the root user can login but cant create database.
maybe create a default database for that
```
create database nextserverdb;
GRANT ALL ON nextserverdb.* TO 'root'@'localhost';
FLUSH PRIVILEGES;
```

**Comment by BoBBer446** [comment]
set chmod rights

**Comment by shoujii** [comment]
Maybe related to https://github.com/shoujii/NeXt-Server/issues/39 ?
