### ISSUE TITLE
WordPress Addon 

### ISSUE THREAD

**Issue by shoujii** [shoujii/NeXt-Server#39]
Add a WordPress addon.

This Issue is not related to the other ones!

**Comment by BoBBer446** [comment]
https://gist.github.com/bgallagh3r/2853221

**Comment by BoBBer446** [comment]
added!

**Comment by shoujii** [comment]
Wenn ich WP installiere, dann kommt auf jeder Seite "Error establishing a database connection"
egal ob domain/nextcloud. domain/wordpress oder nur domain/
Also DB Zugriff scheint durch die WP Install kaputt zu gehen?

domain/pma geht lustigerweise bei mir, wobei Paddy da einen 400 bad request bekommt"Request header or cookie too large

**Comment by BoBBer446** [comment]
Muss getestet werden

**Comment by VeePay** [comment]
Error: Failed to create db

**Comment by BoBBer446** [comment]
Hoffe es klappt jetzt

**Comment by shoujii** [comment]
Working like a charm :)
