### ISSUE TITLE
Generelle Korrektur 

### ISSUE THREAD

**Issue by TiggaStyle** [shoujii/NeXt-Server#41]
Ich hoffe es gehört hier rein und soll nur zum besseren Verständnis des Scriptes und als Anregung Dienen.
DNS Settings 
Wieso steht auf der Seite Verlassen? Da müsste weiter oder OK stehen
Bevor alles bestätigt wird und die Installation startet, kann man schreiben dass es etwas dauert bis alles installiert ist

Please save the shown SSH key ... WO is der? ich kann nur OK drücken. Der wird auf der nächsten Seite/nach dem OK angezeigt.

Wenn er dann angezeigt wird den Key Makiere und ich strg + c drücke bricht alles ab. Sollte man vielleicht eine bessere Methode aufzeigen

Please Save Login, fehlt wieder ein hinweis, das diese nach OK angezeigt werden.

Nextcloud Installation?
Ist installiert, es fehlt ein hinweis: zugangsdaten befinden sich in der login datei

Wordpress?
ist installiert, es fehlt ein hinweis, zugangsdaten befinden sich in der login datei
die wordpress.conf müsste   try_files $uri $uri/ /wordpress/index.php?$args ; beinhalten, ansonsten kann /wordpress nicht aufgerufen werden, man landet durch 301(umleitung) immer auf der Hauptseite.
Der table prefix wp_ sollte in extras anderes geändert werden ggf. Random
zudem sollte der nginx bei WP besser abgesichert werden https://lamosty.com/2015/04/14/securing-your-wordpress-site-running-on-nginx/ bisschen was ist ja in der haupt.conf schon enthalten.

Zudem als Frage: 
Cloud Wordpress - wäre nicer mit eigener URL. Cloud. haupturl oder einer ganz anderen URL. So eher als Vhost mäßig.
Und warum wird alles unter /etc/nginx/html gespeichert und nicht in /var/www ?

Ansonsten lief die Installation des Scriptes, alle Seiten sind aufrufbar und es lässt sich überall einloggen.
Mitlerweile nerft das PINNING, da ja immer ein anderes Zert hinterlegt wird. Aber naja.

Gruß Tigga

**Comment by BoBBer446** [comment]
DNS settings fixed (https://github.com/shoujii/NeXt-Server/commit/31ff83dc1c4019e40f9d9f24ab59e5161dd2d22b)

**Comment by BoBBer446** [comment]
So, sollte alles etwas angepasst worden sein. 

Wordpress Cloud werden wir vorerst nicht implementieren. Vielleicht später. Erstmal haben wir genug Baustellen. Falls ein Pullrequest kommt würden wir den natürlich nicht ablehnen :)
Die Zugangsdaten für Wordpress sind irrelevant, weil Sie direkt eingetragen werden. Allgemein weiß der user bescheid, dass alle Logindaten in der login_information stehen.

Die Ausgabe von Dateien wurde generell mit "ok" statt "verlassen" beschriftet. Weiterhin steht vor den Ausgaben jetzt, dass die Daten auf der nachfolgenden Seite stehen.

der präfix wird noch eingefügt

**Comment by VeePay** [comment]
Vorher konnte der Key und die Login-Information einfach kopiert und extern in einer Datei abgespeichert werden.
Jetzt, da alles im Fenster angezeigt wird, muss der Key nachträglich noch geändert werden (entfernen von #). Zudem können im nächsten Schritt nicht alle Login-infos kopiert werden, da nur ein Teil angezeigt wird.

**Comment by BoBBer446** [comment]
Rollback (237bc0e)

- Wird später mal geändert. Bleibt bei einer nicht GUI ausgabe
