### ISSUE TITLE
Add dialog for read -p "Continue (y/n)?" ANSW

### ISSUE THREAD

**Issue by BoBBer446** [shoujii/NeXt-Server#42]
Put
```
	source ${SCRIPT_PATH}/configuration.sh; show_login_information.txt
	read -p "Continue (y/n)?" ANSW
	if [ "$ANSW" = "n" ]; then
		echo "Exit"
		exit 1
	fi
```

into a dialog output

**Comment by shoujii** [comment]
Ich glaube das es nicht geht, weil dialog Fenster anscheinend immer den kompletten screen bedecken und man die Ausgabe von vorher nicht sieht (ohne zu scrollen).
Das könnte Nutzer verwirren?
