### ISSUE TITLE
The phpMyAdmin configuration storage is not completely configured

### ISSUE THREAD

**Issue by BoBBer446** [shoujii/NeXt-Server#43]
> The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated. Find out why. 
> Or alternately go to 'Operations' tab of any database to set it up there.

> Configuration of pmadb… not OKDocumentation
> General relation features Disabled
>  Create a database named 'phpmyadmin' and setup the phpMyAdmin configuration storage there.

**Comment by shoujii** [comment]
Fixed?! https://github.com/shoujii/NeXt-Server/commit/aab25fb8405403e3c10f79a30b4bfc0759bf5bd4
