### ISSUE TITLE
Webmail, Nextcloud,.. Ordner werden gelöscht

### ISSUE THREAD

**Issue by VeePay** [shoujii/NeXt-Server#47]
Bei der Deinstallation von WordPress über das Skript wird der Ordner Webmail und Nextcloud unter "etc/nginx/html/Domain/" ebenfalls gelöscht. Somit ist ein Ausführen dieser Addons nicht mehr möglich.

**Comment by shoujii** [comment]
rm -rf /etc/nginx/html/${WordpressScriptPath}

Wenn Wordpress in den Root Web Ordner installiert wurde, dann löscht er auch diesen, schauen wir uns an, danke!
