### ISSUE TITLE
PMA funktioniert nicht

### ISSUE THREAD

**Issue by VeePay** [shoujii/NeXt-Server#52]
Nach der Anmeldung "HTTP ERROR 500" -> Diese Seite funktioniert nicht

**Comment by shoujii** [comment]
Der Login geht nur, wenn man bei Server Choice das 2te localhost auswählt, ich werde es mir anschauen!

**Comment by shoujii** [comment]
Das Problem sollte nun auch nicht mehr auftreten :P
