### ISSUE TITLE
Rainloop Error

### ISSUE THREAD

**Issue by VeePay** [shoujii/NeXt-Server#53]
Warning!
RainLoop data folder is accessible. Please configure your web server to hide the data folder from external access. Read more here "https://www.rainloop.net/docs/installation".

**Comment by shoujii** [comment]
Ich konnte es leider bei einer frischen Installation nicht nachvollziehen, wie war denn dein Setup bis das passiert ist? :O

**Comment by VeePay** [comment]
Skript mit PHP7.1 inkl. Webmail und PMA

**Comment by Cr4nkSt4r** [comment]
https://github.com/shoujii/NeXt-Server/issues/59

Fixed!

**Comment by shoujii** [comment]
Stimmt, jetzt sollte es out of the box stimmen 😜
Danke nochmal für die vielen guten tips!
