### ISSUE TITLE
PMA - create new user + new database error

### ISSUE THREAD

**Issue by VeePay** [shoujii/NeXt-Server#54]
no rights can be assigned after creating a new user and datebank.

Error:
#1044 - Access denied for user 'xxx'@'localhost' to database 'xyz'

was logged in with the root user

**Comment by BoBBer446** [comment]
Wie hast du den User und DB erstellt ?

**Comment by shoujii** [comment]
Das sollte nun gefixt sein :)
Falls doch noch Probleme auftreten bitte das Issue neu eröffnen.
