### ISSUE TITLE
Unter PHP 7.2 werfen Seiten die PHP nutzen nur 502 Bad Gateway

### ISSUE THREAD

**Issue by Cr4nkSt4r** [shoujii/NeXt-Server#58]
############### Welche NeXt Server Version wurde installiert?
e600f5bd47790ece1900f474c383528acc42e4ee

############### Welche Module wurden installiert?
PHP 7.2
Mailserver

############### In welcher Reinfolge wurden die Module installiert?
Ganz normal per Script

############### Welche PHP Version wurde installiert?
7.2

############### Mit oder ohne Mailserver?
Mit

############### Welche Fehlermeldung kommt?
502 Bad Gateway

############### Wann bzw. wo tritt sie auf?
Auf jeder Seite die PHP nutzt bzw. bei jeder PHP Datei welche man aufruft

############### Error Reporting Datei per Mail versendet?
Nope

############### !!! Hänge bitte ggf. die Error.log an !!! ###############
Auch nicht nötig, ich kenne den Fix

Lösung:
In der /etc/php/7.2/fpm/pool.d/www.conf steht noch alles richtig drin:
Zeile 36: listen = /run/php/php7.2-fpm.sock

Auch in der php-fpm.conf:
Zeile 17: pid = /run/php/php7.2-fpm.pid

In der /etc/nginx/_php_fastcgi.conf allerdings:
Zeile 4: fastcgi_pass				unix:/var/run/php/php7.1-fpm.sock;

Somit ist der Fix relativ simpel, php7.1-fpm.sock in php7.2-fpm.sock umbenennen, wurde wohl in der config vergessen zu ändern für PHP 7.2.

**Für das Script selber also** 
unter 

> /root/NeXt-Server/configs/nginx

eine weitere "_php_fastcgi7.2.conf" oder aber auch per Variablen dort ergänzen in:
`Zeile 4: fastcgi_pass				unix:/var/run/php/php7.1-fpm.sock;`

Der cp Befehl ist in /script/nginx.sh Zeile 94.

**Comment by shoujii** [comment]
https://github.com/shoujii/NeXt-Server/commit/0a60c23ec75f50ad4c2eafdaa2dfb228e8d80923
Sollte: Error: inet prefix is expected rather than "1.1.1.1"
Gefixt haben.
Die Zeile war falsch bzw hat in der Stretch version auch nichts zu suchen 😂

Den Rest schaue ich mir in laufe des Wochenende an, ich bin gerade bei meiner Freundin und nur am Handy aktiv.

Danke dir wirklich für das Feedback!
Gruß, Marcel

**Comment by Cr4nkSt4r** [comment]
Gerne, immer wieder gerne.
Von Anfang an nutze ich es ja schon auf einem Testserver für alles bei mir und gebe Feedback, ich liebe das Script einfach ^^

**Comment by shoujii** [comment]
https://github.com/shoujii/NeXt-Server/commit/7080aea47c8591644cb77c8e8b857bf058fa263c könnte die if clauses gefixt haben, bei der Buster Version war es sogar schon gefixt... Wenn man mit 2 Versionen arbeitet wird es manchmal echt unübersichtlich 🙈

Die PHP Sachen schaue ich mir an wenn ich daheim bin.
Und das freut mich natürlich wenn du das Script gerne nutzt :)
Ansonsten darfst du auch gerne einen PR machen, 7.1 ist halt in der configs eigentlich standard und es wird via SED dann auf 7.2 geändert wenn der Nutzer 7.2 statt 7.1 installiert.

Gruß, Marcel

**Comment by BoBBer446** [comment]
Danke auch von mir für das Feedback! Bald im Sinne von Frühling nächstes Jahr habe auch ich wieder mehr Zeit. Bis dahin steht das Haus ;p

**Comment by BoBBer446** [comment]
Fixed :)
