### ISSUE TITLE
RainLoop data folder is accessible

### ISSUE THREAD

**Issue by Cr4nkSt4r** [shoujii/NeXt-Server#59]
############### Welche NeXt Server Version wurde installiert?
e600f5bd47790ece1900f474c383528acc42e4ee

############### Welche PHP Version wurde installiert?
7.2

############### Mit oder ohne Mailserver?
Mit

############### Welche Fehlermeldung kommt?
Unter:
https://domain/webmail/?admin#/general
kommt die Meldung:
RainLoop data folder is accessible

Auch hier machen wir es wieder kurz, unter

> /etc/nginx/sites-aviable/domain.conf

Zeilen 16-19:
```
#Rainloop
location ^~ /data {
  deny all;
}
```

Da das ganze jedoch noch im Unterverzeichnis "webmail" liegt, müsste es "location ^~ /webmail/data {" heißen.

**Für das Script selber also unter:**

> /root/NeXt-Server/configs/nginx/vhost

Zeile 23-26:
```
#Rainloop
location ^~ /data {
  deny all;
}
```

**Comment by shoujii** [comment]
Es sollte gefixt sein 
https://github.com/shoujii/NeXt-Server/commit/80916baed73a94cefc9f2f4a0c82a3e9a9102c5c
