### ISSUE TITLE
450 4.7.1 Client host rejected: cannot find your hostname

### ISSUE THREAD

**Issue by Cr4nkSt4r** [shoujii/NeXt-Server#61]
############### Welche NeXt Server Version wurde installiert?
e600f5bd47790ece1900f474c383528acc42e4ee

############### Welche Module wurden installiert?
phpmyadmin

############### Welche PHP Version wurde installiert?
7.2

############### Mit oder ohne Mailserver?
Mit

############### Welche Fehlermeldung kommt?
450 4.7.1 Client host rejected: cannot find your hostname

############### Wann bzw. wo tritt sie auf?
Beim versenden von E-Mails

############### !!! Hänge bitte ggf. die Error.log an !!! ###############
```
Aug 18 01:51:40 mail postfix/postscreen[65214]: CONNECT from [xxx.xx.xx.xx]:47184 to [xxx.xx.xx.xx]:25
Aug 18 01:51:41 mail postfix/postscreen[65214]: PASS OLD [xxx.xx.xx.xx]:47184
Aug 18 01:51:41 mail postfix/smtpd[65217]: warning: hostname mail.domain.de does not resolve to address xxx.xx.xx.xx
Aug 18 01:51:41 mail postfix/smtpd[65217]: connect from unknown[xxx.xx.xx.xx]
Aug 18 01:51:41 mail postfix/smtpd[65217]: warning: connect to Milter service inet:localhost:11332: Connection refused
Aug 18 01:52:46 mail postfix/smtpd[65217]: NOQUEUE: reject: RCPT from unknown[xxx.xx.xx.xx]: 450 4.7.25 Client host rejected: cannot find your hostname, [xxx.xx.xx.xx]; from=<admin@domain.de> to=<admin@domain.de> proto=SMTP helo=<domain.de>

```

per host, dig, dig -x, alles passt zusammen, alles zeigt immer auf die richtige IP und den richtigen host.
```
dig -x xxx.xx.xx.xx +short
mail.domain.de.

host xxx.xx.xx.xx
xx.xx.xx.xxx.in-addr.arpa domain name pointer mail.doamin.de.

host mail.domain.de
mail.domain.de has address xxx.xx.xx.xx
```

Ich habe leider null Plan was E-Mail angeht und habe mich an das Script gehalten.
DNS Einträge sind alle vorhanden wie vorgegeben, DKIM eingetragen aber ich weis leider echt nicht wo ich anfangen soll zu suchen, vielleicht hat ja jemand einen Rat.

### **[EDIT]+FIX**
Okay, eine Idee hatte ich gerade noch und zwar folgende:
In `/etc/postfix/main.cf` stand folgendes:
`mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128`
dort habe ich einfach meine IP-Adresse mit eingetragen:
`mynetworks = 127.0.0.0/8 xxx.xx.xx.xx [::ffff:127.0.0.0]/104 [::1]/128`
Danach postfix restartet und es hat wunderbar funktioniert.

**Comment by shoujii** [comment]
Danke für deine tollen Bug Reports!

Im Moment bin ich alleine am entwickeln des Scripts und kam von Aufwand auch nicht alle Fälle immer testen oder es gehen auch gerne mal Tippfehler über.
Deshalb bin ich dankbar das du alles auf Herz und Nieren testest.
Wenn du magst kam ich dich gerne zum privaten Repo für die Buster Version hinzufügen 🤗

https://github.com/shoujii/NeXt-Server/commit/116ecac4aef969c254e156be23ab8dbaafecf580
Sollte es gefixt haben.
Das changeme wird in der Postfix.sh via SED in den Wert von ipadr Ergo der IP verändert.

Gruß, Marcel
